#!/usr/bin/env pwsh
# milestone-driver - golden-matrix runner for check-citations.ps1 (issue #432).
$Here = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = (Resolve-Path (Join-Path $Here '..')).Path
$Script = Join-Path $Root 'scripts' 'check-citations.ps1'
$Cases = Join-Path $Here 'check-citations.cases.tsv'

$env:GIT_CONFIG_GLOBAL = Join-Path ([System.IO.Path]::GetTempPath()) 'absent-global-gitconfig'
$env:GIT_CONFIG_NOSYSTEM = '1'
$env:GIT_CONFIG_COUNT = '1'
$env:GIT_CONFIG_KEY_0 = 'core.excludesFile'
$env:GIT_CONFIG_VALUE_0 = Join-Path ([System.IO.Path]::GetTempPath()) 'absent-global-gitexcludes'
$Fix = 'tests/fixtures/check-citations'
$Gold = Join-Path $Root $Fix '_expected'
if (-not (Test-Path $Script)) { Write-Error "FATAL: missing $Script"; exit 3 }
if (-not (Test-Path $Cases)) { Write-Error "FATAL: missing $Cases"; exit 3 }
if (-not (Test-Path (Join-Path $Root $Fix))) { Write-Error "FATAL: missing $Root/$Fix"; exit 3 }
$pwshBin = (Get-Command pwsh).Source

$utf8 = [System.Text.UTF8Encoding]::new($false)
$pass = 0; $fail = 0
$ExpectCols = 3

# requires. PowerShell's `-eq` on strings is case-INSENSITIVE and
function Eq-Exact([string]$a, [string]$b) {
  return [string]::Equals($a, $b, [System.StringComparison]::Ordinal)
}

function Show-Escaped([string]$s) {
  if ($null -eq $s) { return '' }
  return ((($s -replace "`r", '\r') -replace "`n", '\n') -replace "`t", '\t')
}

function Read-Golden([string]$name) {
  $path = Join-Path $Gold $name
  if (-not (Test-Path -LiteralPath $path)) {
    Write-Error "FATAL: case names a missing golden: $path"
    exit 3
  }
  return ([System.IO.File]::ReadAllText($path, $utf8) -replace "`r`n", "`n")
}

function Invoke-Checker([string[]]$scriptArgs, [string]$workDir) {
  $psi = [System.Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $pwshBin
  foreach ($a in @('-NoProfile', '-File', $Script)) { [void]$psi.ArgumentList.Add($a) }
  foreach ($a in $scriptArgs) { [void]$psi.ArgumentList.Add($a) }
  $psi.WorkingDirectory = $workDir
  $psi.UseShellExecute = $false
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.StandardOutputEncoding = $utf8
  $psi.StandardErrorEncoding = $utf8
  $p = [System.Diagnostics.Process]::Start($psi)
  $outTask = $p.StandardOutput.ReadToEndAsync()
  $errTask = $p.StandardError.ReadToEndAsync()
  $p.WaitForExit()
  return @{
    out = $outTask.GetAwaiter().GetResult()
    err = $errTask.GetAwaiter().GetResult()
    rc  = $p.ExitCode
  }
}

$caseCount = 0
foreach ($rawRow in Get-Content -LiteralPath $Cases) {
  $row = $rawRow -replace "`r$", ''
  if ($row -eq '' -or $row.StartsWith('#')) { continue }
  $cols = $row -split "`t"
  if ($cols.Count -ne $ExpectCols) {
    Write-Error "FATAL: row failed to parse (got $($cols.Count) fields, want $ExpectCols): [$row]"
    exit 1
  }
  $caseCount++
  $name = $cols[0]; $golden = $cols[1]; $wantExit = [int]$cols[2]

  $expOut = Read-Golden $golden
  $r = Invoke-Checker @("$Fix/$name") $Root

  if ($r.rc -eq $wantExit -and (Eq-Exact $r.out $expOut) -and (Eq-Exact $r.err '')) { $pass++ }
  else {
    $fail++
    Write-Host "FAIL ${name}: rc=$($r.rc) (want $wantExit)"
    Write-Host "  out got  [$(Show-Escaped $r.out)]"
    Write-Host "  out want [$(Show-Escaped $expOut)]"
    Write-Host "  err got  [$(Show-Escaped $r.err)] (want empty)"
  }
}

if ($caseCount -eq 0) {
  Write-Error "FATAL: parsed 0 cases from $Cases - this run tested nothing"
  exit 1
}

# ---- bespoke: a REPO_ROOT that is not a directory. The stderr golden is SHARED
$wantErr = Read-Golden 'missing-root.stderr.txt'
$r = Invoke-Checker @("$Fix/no-such-root") $Root
if ($r.rc -eq 1 -and (Eq-Exact $r.out '') -and (Eq-Exact $r.err $wantErr)) { $pass++ }
else {
  $fail++
  Write-Host "FAIL missing-root: rc=$($r.rc) (want 1)"
  Write-Host "  out got  [$(Show-Escaped $r.out)] (want empty)"
  Write-Host "  err got  [$(Show-Escaped $r.err)]"
  Write-Host "  err want [$(Show-Escaped $wantErr)]"
}

# ---- bespoke: NO argument at all, run from inside the fixture root. The table
$expOut = Read-Golden 'resolves-once.txt'
$r = Invoke-Checker @() (Join-Path $Root $Fix 'resolves-once')
if ($r.rc -eq 0 -and (Eq-Exact $r.out $expOut) -and (Eq-Exact $r.err '')) { $pass++ }
else {
  $fail++
  Write-Host "FAIL default-root: rc=$($r.rc) (want 0)"
  Write-Host "  out got  [$(Show-Escaped $r.out)]"
  Write-Host "  out want [$(Show-Escaped $expOut)]"
  Write-Host "  err got  [$(Show-Escaped $r.err)] (want empty)"
}

# ---- bespoke: GENERATED byte-level trees ------------------------------------
$Tmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid().ToString())
New-Item -ItemType Directory -Path $Tmp -Force | Out-Null
$Latin1 = [System.Text.Encoding]::Latin1

function Write-Raw([string]$path, [string]$byteChars) {
  [System.IO.File]::WriteAllBytes($path, $Latin1.GetBytes($byteChars))
}

function Cite([int]$n, [string]$path, [string]$anchor) { return "$n ``$path ($anchor)```n" }

function Build-GenBytes([string]$b) {
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'docs') -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'src') -Force | Out-Null
  $e9 = [string][char]0xE9
  Write-Raw (Join-Path $b 'outside.md') "secret string`n"
  Write-Raw (Join-Path $b 'gen' 'docs' 'citing.md') (
    "# Citing`n`n" +
    (Cite 1 'src/crlf.md'      'crlf anchor here') +
    (Cite 2 'src/bom.md'       'bom anchor') +
    (Cite 3 'src/nonewline.md' 'tail anchor') +
    (Cite 4 'src/highbyte.md'  "caf$e9 anchor") +
    (Cite 5 'src/utf16.md'     'utf16 anchor') +
    (Cite 6 '../outside.md'    'secret string'))
  Write-Raw (Join-Path $b 'gen' 'src' 'crlf.md') "# Crlf`r`ncrlf anchor here`r`n"
  $bom = [string][char]0xEF + [string][char]0xBB + [string][char]0xBF
  Write-Raw (Join-Path $b 'gen' 'src' 'bom.md') ($bom + "bom anchor on line one`n")
  Write-Raw (Join-Path $b 'gen' 'src' 'nonewline.md') "# Tail`ntail anchor"
  Write-Raw (Join-Path $b 'gen' 'src' 'highbyte.md') "# High`ncaf$e9 anchor lives here`n"
  $u16 = [string][char]0xFF + [string][char]0xFE
  foreach ($c in "utf16 anchor`n".ToCharArray()) { $u16 += [string]$c + [string][char]0 }
  Write-Raw (Join-Path $b 'gen' 'src' 'utf16.md') $u16
}

function Build-GenIgnored([string]$b) {
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'docs') -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'src') -Force | Out-Null
  $git = Get-Command git -ErrorAction SilentlyContinue
  if ($null -eq $git) { return $false }
  & $git.Source 'init' '-q' (Join-Path $b 'gen') 2>$null | Out-Null
  if ($LASTEXITCODE -ne 0) { return $false }
  Write-Raw (Join-Path $b 'gen' '.gitignore') "scratch.md`n"
  Write-Raw (Join-Path $b 'gen' 'docs' 'citing.md') (
    "# Citing`n`n" + (Cite 1 'src/target.md' 'live anchor'))
  Write-Raw (Join-Path $b 'gen' 'scratch.md') (
    "# Scratch`n`n" + (Cite 1 'src/target.md' 'anchor that was reworded away'))
  Write-Raw (Join-Path $b 'gen' 'src' 'target.md') "# Target`nlive anchor lives here`n"
  return $true
}

function Build-GenUnix([string]$b) {
  if ($IsWindows) { return $false }
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'docs') -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'src') -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $b 'gen' 'locked') -Force | Out-Null
  Write-Raw (Join-Path $b 'gen' 'docs' 'citing.md') (
    "# Citing`n`n" +
    (Cite 1 'src/real.md' 'real anchor') +
    (Cite 2 'src/link.md' 'real anchor') +
    (Cite 3 'src/pipe.md' 'any anchor'))
  Write-Raw (Join-Path $b 'gen' 'src' 'real.md') "# Real`nreal anchor lives here`n"
  Write-Raw (Join-Path $b 'gen' 'locked' 'plain.md') "# Plain`nNothing worth citing.`n"
  try {
    New-Item -ItemType SymbolicLink -Path (Join-Path $b 'gen' 'src' 'link.md') -Target 'real.md' -ErrorAction Stop | Out-Null
    $mk = Get-Command mkfifo -ErrorAction SilentlyContinue
    if ($null -eq $mk) { return $false }
    & $mk.Source (Join-Path $b 'gen' 'src' 'pipe.md')
    if ($LASTEXITCODE -ne 0) { return $false }
    [System.IO.File]::SetUnixFileMode((Join-Path $b 'gen' 'locked'), [System.IO.UnixFileMode]::None)
  } catch { return $false }
  return $true
}

function Invoke-Generated([string]$gname, [string]$groot, [string]$ggold, [int]$gwant) {
  $gexp = Read-Golden $ggold
  $r = Invoke-Checker @($groot) $Root
  if ($r.rc -eq $gwant -and (Eq-Exact $r.out $gexp) -and (Eq-Exact $r.err '')) {
    $script:pass++
  } else {
    $script:fail++
    Write-Host "FAIL ${gname}: rc=$($r.rc) (want $gwant)"
    Write-Host "  out got  [$(Show-Escaped $r.out)]"
    Write-Host "  out want [$(Show-Escaped $gexp)]"
    Write-Host "  err got  [$(Show-Escaped $r.err)] (want empty)"
  }
}

Build-GenBytes $Tmp
Invoke-Generated 'gen-bytes' (Join-Path $Tmp 'gen') 'gen-bytes.txt' 1

$unixTmp = Join-Path $Tmp 'u'
New-Item -ItemType Directory -Path $unixTmp -Force | Out-Null
$genUnixRan = Build-GenUnix $unixTmp
if ($genUnixRan) {
  Invoke-Generated 'gen-unix' (Join-Path $unixTmp 'gen') 'gen-unix.txt' 1
}
$ignTmp = Join-Path $Tmp 'i'
New-Item -ItemType Directory -Path $ignTmp -Force | Out-Null
$genIgnoredRan = Build-GenIgnored $ignTmp
if ($genIgnoredRan) {
  Invoke-Generated 'gen-ignored' (Join-Path $ignTmp 'gen') 'gen-ignored.txt' 0
}

try {
  $lk = Join-Path $unixTmp 'gen' 'locked'
  if (Test-Path -LiteralPath $lk) {
    [System.IO.File]::SetUnixFileMode($lk, [System.IO.UnixFileMode]'UserRead,UserWrite,UserExecute')
  }
} catch { }
Remove-Item -Recurse -Force $Tmp -ErrorAction SilentlyContinue

$bespoke = 5
$skipNote = ''
if (-not $genUnixRan) { $bespoke--; $skipNote += ', gen-unix SKIPPED on this platform' }
if (-not $genIgnoredRan) { $bespoke--; $skipNote += ', gen-ignored SKIPPED (no usable git)' }
Write-Host "check-citations.ps1: $pass passed, $fail failed (parsed $caseCount TSV cases + $bespoke bespoke$skipNote)"
if ($fail -ne 0) { exit 1 }
