#!/usr/bin/env bash
# milestone-driver - golden-matrix runner for check-citations.sh (issue #432).
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
SCRIPT="$ROOT/scripts/check-citations.sh"
CASES="$HERE/check-citations.cases.tsv"
FIX="tests/fixtures/check-citations"
GOLD="$ROOT/$FIX/_expected"
[ -f "$SCRIPT" ] || { echo "FATAL: missing $SCRIPT" >&2; exit 3; }
[ -f "$CASES" ] || { echo "FATAL: missing $CASES" >&2; exit 3; }
[ -d "$ROOT/$FIX" ] || { echo "FATAL: missing $ROOT/$FIX" >&2; exit 3; }
BASH_BIN="$(command -v bash)"

pass=0; fail=0
TMP="$(mktemp -d 2>/dev/null || echo "${TMPDIR:-/tmp}/cct.$$")"; mkdir -p "$TMP"
trap 'rm -rf "$TMP"' EXIT
export GIT_CONFIG_GLOBAL="$TMP/absent-global-gitconfig"
export GIT_CONFIG_NOSYSTEM=1
export GIT_CONFIG_COUNT=1
export GIT_CONFIG_KEY_0=core.excludesFile
export GIT_CONFIG_VALUE_0="$TMP/absent-global-gitexcludes"

OUTFILE="$TMP/out"
ERRFILE="$TMP/err"

TAB=$'\t'
EXPECT_COLS=3
split_tab() {
  local rest="$1$TAB"
  cols=()
  while [ -n "$rest" ]; do cols+=("${rest%%"$TAB"*}"); rest="${rest#*"$TAB"}"; done
}

slurp_x() { cat "$1"; printf X; }

read_golden() {
  [ -f "$GOLD/$1" ] || { echo "FATAL: case names a missing golden: $GOLD/$1" >&2; exit 3; }
  local g; g="$(slurp_x "$GOLD/$1")"; g="${g%X}"
  printf '%sX' "${g//$'\r\n'/$'\n'}"
}

cd "$ROOT"

case_count=0
while IFS= read -r row || [ -n "$row" ]; do
  row="${row%$'\r'}"
  case "$row" in ''|\#*) continue;; esac
  split_tab "$row"
  if [ "${#cols[@]}" -ne "$EXPECT_COLS" ]; then
    echo "FATAL: row failed to parse (got ${#cols[@]} fields, want $EXPECT_COLS): [$row]" >&2
    exit 1
  fi
  case_count=$((case_count+1))
  name="${cols[0]}"; golden="${cols[1]}"; want_exit="${cols[2]}"

  exp_out="$(read_golden "$golden")"; exp_out="${exp_out%X}"
  "$BASH_BIN" "$SCRIPT" "$FIX/$name" >"$OUTFILE" 2>"$ERRFILE"; rc=$?
  out="$(slurp_x "$OUTFILE")"; out="${out%X}"
  err="$(slurp_x "$ERRFILE")"; err="${err%X}"

  if [ "$rc" -eq "$want_exit" ] && [ "$out" = "$exp_out" ] && [ -z "$err" ]; then
    pass=$((pass+1))
  else
    fail=$((fail+1))
    printf 'FAIL %s: rc=%s (want %s)\n' "$name" "$rc" "$want_exit" >&2
    diff <(printf '%s' "$exp_out" | od -c) <(printf '%s' "$out" | od -c) >&2 || true
    printf '  stderr got[%s] (want empty)\n' "$err" >&2
  fi
done < "$CASES"

if [ "$case_count" -eq 0 ]; then
  echo "FATAL: parsed 0 cases from $CASES - this run tested nothing" >&2
  exit 1
fi

# ---- bespoke: a REPO_ROOT that is not a directory. Fail-loud, and the stderr
ROOT_GOLD="$GOLD/missing-root.stderr.txt"
if [ ! -f "$ROOT_GOLD" ]; then
  echo "FATAL: missing golden $ROOT_GOLD" >&2; fail=$((fail+1))
else
  want_err="$(slurp_x "$ROOT_GOLD")"; want_err="${want_err%X}"
  want_err="${want_err//$'\r\n'/$'\n'}"
  "$BASH_BIN" "$SCRIPT" "$FIX/no-such-root" >"$OUTFILE" 2>"$ERRFILE"; rc=$?
  out="$(slurp_x "$OUTFILE")"; out="${out%X}"
  err="$(slurp_x "$ERRFILE")"; err="${err%X}"
  if [ "$rc" -eq 1 ] && [ -z "$out" ] && [ "$err" = "$want_err" ]; then
    pass=$((pass+1))
  else
    fail=$((fail+1))
    printf 'FAIL missing-root: rc=%s (want 1) stdout=[%s] (want empty)\n' "$rc" "$out" >&2
    printf '  stderr got[%s] want[%s]\n' "$err" "$want_err" >&2
  fi
fi

# ---- bespoke: NO argument at all, run from inside the fixture root. The table
exp_out="$(read_golden "resolves-once.txt")"; exp_out="${exp_out%X}"
( cd "$ROOT/$FIX/resolves-once" && "$BASH_BIN" "$SCRIPT" >"$OUTFILE" 2>"$ERRFILE" ); rc=$?
out="$(slurp_x "$OUTFILE")"; out="${out%X}"
err="$(slurp_x "$ERRFILE")"; err="${err%X}"
if [ "$rc" -eq 0 ] && [ "$out" = "$exp_out" ] && [ -z "$err" ]; then
  pass=$((pass+1))
else
  fail=$((fail+1))
  printf 'FAIL default-root: rc=%s (want 0)\n' "$rc" >&2
  diff <(printf '%s' "$exp_out" | od -c) <(printf '%s' "$out" | od -c) >&2 || true
  printf '  stderr got[%s] (want empty)\n' "$err" >&2
fi

# ---- bespoke: GENERATED byte-level trees ------------------------------------

cite_line() { printf '%s `%s (%s)`\n' "$1" "$2" "$3"; }

build_gen_bytes() {
  b="$1"
  mkdir -p "$b/gen/docs" "$b/gen/src"
  e9="$(printf '\351')"
  printf 'secret string\n' > "$b/outside.md"
  {
    printf '# Citing\n\n'
    cite_line 1 'src/crlf.md'      'crlf anchor here'
    cite_line 2 'src/bom.md'       'bom anchor'
    cite_line 3 'src/nonewline.md' 'tail anchor'
    cite_line 4 'src/highbyte.md'  "caf$e9 anchor"
    cite_line 5 'src/utf16.md'     'utf16 anchor'
    cite_line 6 '../outside.md'    'secret string'
  } > "$b/gen/docs/citing.md"
  printf '# Crlf\r\ncrlf anchor here\r\n' > "$b/gen/src/crlf.md"
  printf '\357\273\277bom anchor on line one\n' > "$b/gen/src/bom.md"
  printf '# Tail\ntail anchor' > "$b/gen/src/nonewline.md"
  printf '# High\ncaf\351 anchor lives here\n' > "$b/gen/src/highbyte.md"
  printf '\377\376u\000t\000f\0001\0006\000 \000a\000n\000c\000h\000o\000r\000\n\000' > "$b/gen/src/utf16.md"
}

build_gen_unix() {
  b="$1"
  mkdir -p "$b/gen/docs" "$b/gen/src" "$b/gen/locked"
  {
    printf '# Citing\n\n'
    cite_line 1 'src/real.md' 'real anchor'
    cite_line 2 'src/link.md' 'real anchor'
    cite_line 3 'src/pipe.md' 'any anchor'
  } > "$b/gen/docs/citing.md"
  printf '# Real\nreal anchor lives here\n' > "$b/gen/src/real.md"
  printf '# Plain\nNothing worth citing.\n' > "$b/gen/locked/plain.md"
  ln -s real.md "$b/gen/src/link.md" || return 1
  mkfifo "$b/gen/src/pipe.md" || return 1
  chmod 000 "$b/gen/locked" || return 1
  return 0
}

build_gen_ignored() {
  b="$1"
  mkdir -p "$b/gen/docs" "$b/gen/src"
  git init -q "$b/gen" 2>/dev/null || return 1
  printf 'scratch.md\n' > "$b/gen/.gitignore"
  {
    printf '# Citing\n\n'
    cite_line 1 'src/target.md' 'live anchor'
  } > "$b/gen/docs/citing.md"
  {
    printf '# Scratch\n\n'
    cite_line 1 'src/target.md' 'anchor that was reworded away'
  } > "$b/gen/scratch.md"
  printf '# Target\nlive anchor lives here\n' > "$b/gen/src/target.md"
  return 0
}

run_generated() {
  gname="$1"; groot="$2"; ggold="$3"; gwant="$4"
  gexp="$(read_golden "$ggold")"; gexp="${gexp%X}"
  "$BASH_BIN" "$SCRIPT" "$groot" >"$OUTFILE" 2>"$ERRFILE"; grc=$?
  gout="$(slurp_x "$OUTFILE")"; gout="${gout%X}"
  gerr="$(slurp_x "$ERRFILE")"; gerr="${gerr%X}"
  if [ "$grc" -eq "$gwant" ] && [ "$gout" = "$gexp" ] && [ -z "$gerr" ]; then
    pass=$((pass+1))
  else
    fail=$((fail+1))
    printf 'FAIL %s: rc=%s (want %s)\n' "$gname" "$grc" "$gwant" >&2
    diff <(printf '%s' "$gexp" | od -c) <(printf '%s' "$gout" | od -c) >&2 || true
    printf '  stderr got[%s] (want empty)\n' "$gerr" >&2
  fi
}

build_gen_bytes "$TMP"
run_generated gen-bytes "$TMP/gen" gen-bytes.txt 1

UNIXTMP="$TMP/u"
mkdir -p "$UNIXTMP"
gen_unix_skipped=0
if build_gen_unix "$UNIXTMP" 2>/dev/null; then
  run_generated gen-unix "$UNIXTMP/gen" gen-unix.txt 1
  chmod 755 "$UNIXTMP/gen/locked" 2>/dev/null || true
else
  gen_unix_skipped=1
  chmod 755 "$UNIXTMP/gen/locked" 2>/dev/null || true
fi

IGNTMP="$TMP/i"
mkdir -p "$IGNTMP"
gen_ignored_skipped=0
if build_gen_ignored "$IGNTMP"; then
  run_generated gen-ignored "$IGNTMP/gen" gen-ignored.txt 0
else
  gen_ignored_skipped=1
fi

bespoke=5
skipnote=''
if [ "$gen_unix_skipped" -eq 1 ]; then
  bespoke=$((bespoke - 1)); skipnote="$skipnote, gen-unix SKIPPED on this platform"
fi
if [ "$gen_ignored_skipped" -eq 1 ]; then
  bespoke=$((bespoke - 1)); skipnote="$skipnote, gen-ignored SKIPPED (no usable git)"
fi
echo "check-citations.sh: $pass passed, $fail failed (parsed $case_count TSV cases + $bespoke bespoke$skipnote)"
[ "$fail" -eq 0 ]
